# Brogrammer Plus
[colors]
foreground = "#fbfbfb"
background = "#121212"
cursor_bg = "#ffffff"
cursor_border = "#ffffff"
cursor_fg = "#121212"
selection_bg = "#264f78"
selection_fg = "#fcfcfc"

ansi = ["#121212","#e74c3c","#2ecc71","#f1c40f","#3498db","#6c71c4","#3cc9d6","#fbfbfb"]
brights = ["#373737","#ff5542","#3bfb9d","#ffd60d","#48c0ff","#9ea7ff","#51f1ff","#ffffff"]
